# This is a basic workflow, it needs to be completed

name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: lint R Markdown 
        run: |
          cd bin/
          Rscript -e "rmarkdown::render('initial_analysis.Rmd')"
